services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://user:password@db:5432/mydatabase?sslmode=disable
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "go run db/migrations/migrate.go && go run main.go"

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
